project_id = "bacoamhbatqpxatrrflz"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.process-email-queue]
    verify_jwt = true
  [functions.cleanup-exams]
    verify_jwt = false
  [functions.ai-coach]
    verify_jwt = true
  [functions.payos-webhook]
    verify_jwt = false
