// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/search-vocabulary.ts
import { createClient } from "npm:@supabase/supabase-js@^2.108.2";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
var search_vocabulary_default = defineTool({
  name: "search_vocabulary",
  title: "Tra t\u1EEB v\u1EF1ng Aptis",
  description: "T\xECm m\u1ED9t t\u1EEB ti\u1EBFng Anh trong b\u1ED9 t\u1EEB v\u1EF1ng Aptis K\u1EF3 T\xEDch. Tr\u1EA3 v\u1EC1 phi\xEAn \xE2m, ngh\u0129a ti\u1EBFng Vi\u1EC7t, v\xED d\u1EE5 v\xE0 h\u1ECD t\u1EEB.",
  inputSchema: {
    word: z.string().min(1).describe("T\u1EEB ti\u1EBFng Anh c\u1EA7n tra (v\xED d\u1EE5: 'reliable').")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ word }) => {
    const url = process.env.SUPABASE_URL;
    const key = process.env.SUPABASE_PUBLISHABLE_KEY;
    const supabase = createClient(url, key, { auth: { persistSession: false } });
    const { data, error } = await supabase.from("system_vocab_words").select("word, phonetic, meaning, example_en, example_vi, word_family").ilike("word", word.trim()).limit(5);
    if (error) {
      return { content: [{ type: "text", text: `L\u1ED7i: ${error.message}` }], isError: true };
    }
    if (!data?.length) {
      return {
        content: [{ type: "text", text: `Kh\xF4ng t\xECm th\u1EA5y "${word}" trong b\u1ED9 t\u1EEB v\u1EF1ng Aptis K\u1EF3 T\xEDch.` }]
      };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { results: data }
    };
  }
});

// src/lib/mcp/tools/list-exam-sets.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.108.2";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.25.76";
var list_exam_sets_default = defineTool2({
  name: "list_exam_sets",
  title: "Danh s\xE1ch \u0111\u1EC1 Aptis \u0111\xE3 c\xF4ng b\u1ED1",
  description: "Li\u1EC7t k\xEA c\xE1c \u0111\u1EC1 luy\u1EC7n thi Aptis \u0111\xE3 \u0111\u01B0\u1EE3c c\xF4ng b\u1ED1 (is_published = true) tr\xEAn Aptis K\u1EF3 T\xEDch. C\xF3 th\u1EC3 l\u1ECDc theo k\u1EF9 n\u0103ng (reading, listening, writing, speaking, grammar) v\xE0 part.",
  inputSchema: {
    skill: z2.enum(["reading", "listening", "writing", "speaking", "grammar"]).nullable().describe("L\u1ECDc theo k\u1EF9 n\u0103ng. Truy\u1EC1n null \u0111\u1EC3 l\u1EA5y t\u1EA5t c\u1EA3."),
    part: z2.string().nullable().describe("L\u1ECDc theo part (v\xED d\u1EE5 '1'). Truy\u1EC1n null \u0111\u1EC3 l\u1EA5y t\u1EA5t c\u1EA3."),
    limit: z2.number().int().min(1).max(50).describe("S\u1ED1 l\u01B0\u1EE3ng \u0111\u1EC1 t\u1ED1i \u0111a tr\u1EA3 v\u1EC1 (1\u201350).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ skill, part, limit }) => {
    const supabase = createClient2(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY,
      { auth: { persistSession: false } }
    );
    let q = supabase.from("exam_sets").select("id, title, skill, part, exam_type, time_limit, description, created_at").eq("is_published", true).order("created_at", { ascending: false }).limit(limit);
    if (skill) q = q.eq("skill", skill);
    if (part) q = q.eq("part", part);
    const { data, error } = await q;
    if (error) {
      return { content: [{ type: "text", text: `L\u1ED7i: ${error.message}` }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { exam_sets: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-exam-set.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.108.2";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^3.25.76";
var get_exam_set_default = defineTool3({
  name: "get_exam_set",
  title: "Chi ti\u1EBFt \u0111\u1EC1 Aptis",
  description: "L\u1EA5y chi ti\u1EBFt m\u1ED9t \u0111\u1EC1 Aptis \u0111\xE3 c\xF4ng b\u1ED1 k\xE8m danh s\xE1ch c\xE2u h\u1ECFi. Ch\u1EC9 tr\u1EA3 k\u1EBFt qu\u1EA3 cho \u0111\u1EC1 is_published = true.",
  inputSchema: {
    exam_set_id: z3.string().uuid().describe("UUID c\u1EE7a exam_set (l\u1EA5y t\u1EEB list_exam_sets).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ exam_set_id }) => {
    const supabase = createClient3(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY,
      { auth: { persistSession: false } }
    );
    const { data: examSet, error: setErr } = await supabase.from("exam_sets").select("id, title, skill, part, exam_type, time_limit, description, is_published").eq("id", exam_set_id).eq("is_published", true).maybeSingle();
    if (setErr) {
      return { content: [{ type: "text", text: `L\u1ED7i: ${setErr.message}` }], isError: true };
    }
    if (!examSet) {
      return {
        content: [{ type: "text", text: "Kh\xF4ng t\xECm th\u1EA5y \u0111\u1EC1, ho\u1EB7c \u0111\u1EC1 ch\u01B0a \u0111\u01B0\u1EE3c c\xF4ng b\u1ED1." }],
        isError: true
      };
    }
    const { data: questions, error: qErr } = await supabase.from("exam_questions").select("id, order_index, question_text, question_type, options, correct_answer").eq("exam_set_id", exam_set_id).order("order_index", { ascending: true });
    if (qErr) {
      return { content: [{ type: "text", text: `L\u1ED7i: ${qErr.message}` }], isError: true };
    }
    const payload = { exam_set: examSet, questions: questions ?? [] };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "aptis-ky-tich-mcp",
  title: "Aptis K\u1EF3 T\xEDch MCP",
  version: "0.1.0",
  instructions: "C\xF4ng c\u1EE5 truy c\u1EADp n\u1ED9i dung c\xF4ng khai c\u1EE7a Aptis K\u1EF3 T\xEDch \u2014 n\u1EC1n t\u1EA3ng luy\u1EC7n thi Aptis General cho ng\u01B0\u1EDDi Vi\u1EC7t. D\xF9ng `search_vocabulary` \u0111\u1EC3 tra t\u1EEB v\u1EF1ng, `list_exam_sets` \u0111\u1EC3 duy\u1EC7t c\xE1c \u0111\u1EC1 \u0111\xE3 c\xF4ng b\u1ED1 theo k\u1EF9 n\u0103ng/part, v\xE0 `get_exam_set` \u0111\u1EC3 l\u1EA5y chi ti\u1EBFt c\xE2u h\u1ECFi c\u1EE7a m\u1ED9t \u0111\u1EC1. Ch\u1EC9 d\u1EEF li\u1EC7u is_published = true \u0111\u01B0\u1EE3c tr\u1EA3 v\u1EC1.",
  tools: [search_vocabulary_default, list_exam_sets_default, get_exam_set_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
