import { createClient } from "https://esm.sh/@supabase/supabase-js@2.45.0";
import { logUsage, logInvocation } from "../_shared/usage-logger.ts";
import { requireUser } from "../_shared/auth.ts";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers":
    "authorization, x-client-info, apikey, content-type, x-supabase-client-platform, x-supabase-client-platform-version, x-supabase-client-runtime, x-supabase-client-runtime-version",
};

const ELEVENLABS_VOICE_ID = "ET1Y16dAzb7BWkm9Bmxh";

const VOICE_CONFIG = {
  en: { languageCode: "en-US", name: "en-US-Neural2-J" },
  vi: { languageCode: "vi-VN", name: "vi-VN-Neural2-A" },
} as const;


// Simple stable hash (FNV-1a 32-bit) — fine for cache key
function hash(str: string): string {
  let h = 0x811c9dc5;
  for (let i = 0; i < str.length; i++) {
    h ^= str.charCodeAt(i);
    h = Math.imul(h, 0x01000193) >>> 0;
  }
  return h.toString(16).padStart(8, "0");
}

function buildCacheKey(text: string, lang: string, voice: string): string {
  const normalized = text.trim().toLowerCase().replace(/\s+/g, " ");
  return `${hash(normalized + "|" + lang + "|" + voice)}_${normalized.slice(0, 24).replace(/[^a-z0-9]+/g, "-")}`;
}

function base64ToBytes(b64: string): Uint8Array {
  const bin = atob(b64);
  const out = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) out[i] = bin.charCodeAt(i);
  return out;
}

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response("ok", { headers: corsHeaders });
  }

  // Require authenticated user to prevent unauthenticated cost abuse of the
  // paid Google TTS API. Unique-text requests bypass cache and are billed
  // per character, so open access would let anyone drive up costs.
  const auth = await requireUser(req, corsHeaders);
  if (auth instanceof Response) return auth;
  logInvocation("tts").catch(() => {});

  try {
    const body = await req.json().catch(() => ({}));
    const text = typeof body.text === "string" ? body.text.trim() : "";
    const lang = body.lang === "vi" ? "vi" : "en";
    const surface = body.surface === "exam" ? "exam" : "app";
    const cfg = VOICE_CONFIG[lang];
    const voice = typeof body.voice === "string" && body.voice ? body.voice : cfg.name;

    if (!text || text.length > 1000) {
      return new Response(JSON.stringify({ error: "Invalid text" }), {
        status: 400,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    const supabase = createClient(
      Deno.env.get("SUPABASE_URL")!,
      Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!
    );

    // Provider + voice are part of the cache path so switching voices never
    // serves audio generated by the previous provider. Old cache stays intact.
    const provider = surface === "exam" ? "elevenlabs" : "openai";
    const voiceId = surface === "exam" ? ELEVENLABS_VOICE_ID : "onyx";
    const cacheKey = buildCacheKey(text, lang, `${provider}|${voiceId}`);
    const path = `${lang}/${provider}_${voiceId}/${cacheKey}.mp3`;

    // Check cache via public URL (HEAD)
    const { data: pub } = supabase.storage.from("tts-cache").getPublicUrl(path);
    const url = pub.publicUrl;

    const head = await fetch(url, { method: "HEAD" });
    if (head.ok) {
      return new Response(JSON.stringify({ url, cached: true }), {
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    let audioBuffer: ArrayBuffer | null = null;
    let usedProvider = provider;

    if (surface === "exam") {
      const elevenKey = Deno.env.get("ELEVENLABS_API_KEY");
      if (!elevenKey) {
        console.error("[tts] ELEVENLABS_API_KEY missing — falling back to OpenAI voice");
      } else {
        try {
          const elRes = await fetch(
            `https://api.elevenlabs.io/v1/text-to-speech/${ELEVENLABS_VOICE_ID}`,
            {
              method: "POST",
              headers: {
                "xi-api-key": elevenKey,
                "Content-Type": "application/json",
                Accept: "audio/mpeg",
              },
              body: JSON.stringify({
                text,
                model_id: "eleven_multilingual_v2",
                voice_settings: {
                  stability: 0.5,
                  similarity_boost: 0.75,
                  style: 0,
                  use_speaker_boost: true,
                },
              }),
            },
          );
          if (elRes.ok) {
            audioBuffer = await elRes.arrayBuffer();
          } else {
            const errText = await elRes.text().catch(() => "");
            const kind = elRes.status === 401 || elRes.status === 403
              ? "auth"
              : elRes.status === 402
              ? "credit"
              : elRes.status === 429
              ? "rate limit"
              : elRes.status >= 500
              ? "upstream"
              : "request";
            console.error(`[tts] ElevenLabs ${kind} failure (${elRes.status}) — falling back to OpenAI voice:`, errText);
          }
        } catch (e) {
          console.error("[tts] ElevenLabs network failure — falling back to OpenAI voice:", e);
        }
      }
      if (audioBuffer) {
        logUsage({
          service: "elevenlabs_tts",
          event_type: "tts_synthesis",
          units: text.length,
          unit_type: "chars",
          source_function: "tts",
          metadata: { lang, voice: ELEVENLABS_VOICE_ID, model: "eleven_multilingual_v2" },
        }).catch(() => {});
      } else {
        usedProvider = "openai";
      }
    }

    if (audioBuffer) {
      const bytes = new Uint8Array(audioBuffer);
      const { error: upErr } = await supabase.storage
        .from("tts-cache")
        .upload(path, bytes, { contentType: "audio/mpeg", upsert: true, cacheControl: "31536000" });
      if (upErr) {
        console.error("Upload error:", upErr);
        return new Response(JSON.stringify({ error: "Upload failed", detail: upErr.message }), {
          status: 500,
          headers: { ...corsHeaders, "Content-Type": "application/json" },
        });
      }
      return new Response(JSON.stringify({ url, cached: false, provider: usedProvider }), {
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }


    // OpenAI branch: surface "app", or ElevenLabs auth/credit failure fallback.
    const oaPath = `${lang}/openai_onyx/${buildCacheKey(text, lang, "openai|onyx")}.mp3`;
    const oaUrl = supabase.storage.from("tts-cache").getPublicUrl(oaPath).data.publicUrl;
    if (oaPath !== path) {
      const oaHead = await fetch(oaUrl, { method: "HEAD" });
      if (oaHead.ok) {
        return new Response(JSON.stringify({ url: oaUrl, cached: true, provider: "openai" }), {
          headers: { ...corsHeaders, "Content-Type": "application/json" },
        });
      }
    }

    // Not cached — synthesize via Lovable AI (OpenAI-compatible /audio/speech)
    const lovableKey = Deno.env.get("LOVABLE_API_KEY");
    if (!lovableKey) {
      return new Response(JSON.stringify({ error: "Missing LOVABLE_API_KEY" }), {
        status: 500,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    const ttsRes = await fetch("https://ai.gateway.lovable.dev/v1/audio/speech", {
      method: "POST",
      headers: {
        Authorization: `Bearer ${lovableKey}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        model: "openai/gpt-4o-mini-tts",
        input: text,
        voice: "onyx",
        response_format: "mp3",
        speed: 0.95,
        instructions:
          lang === "vi"
            ? "Speak in natural Vietnamese, clear and calm."
            : "Speak in a clear British English accent, calm exam-instruction tone.",
      }),
    });

    if (!ttsRes.ok) {
      const errText = await ttsRes.text().catch(() => "");
      console.error("Lovable AI TTS error:", ttsRes.status, errText);
      const status = ttsRes.status === 429 || ttsRes.status === 402 ? ttsRes.status : 502;
      return new Response(
        JSON.stringify({ error: "TTS service temporarily unavailable", status: ttsRes.status, details: errText }),
        { status, headers: { ...corsHeaders, "Content-Type": "application/json" } },
      );
    }

    const oaBuffer = await ttsRes.arrayBuffer();
    if (!oaBuffer.byteLength) {
      return new Response(JSON.stringify({ error: "No audio returned" }), {
        status: 502,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }


    // Log TTS usage (chars)
    logUsage({
      service: "lovable_ai_tts",
      event_type: "tts_synthesis",
      units: text.length,
      unit_type: "chars",
      source_function: "tts",
      metadata: { lang, voice, model: "openai/gpt-4o-mini-tts" },
    }).catch(() => {});

    const bytes = new Uint8Array(oaBuffer);

    const { error: upErr } = await supabase.storage
      .from("tts-cache")
      .upload(oaPath, bytes, {
        contentType: "audio/mpeg",
        upsert: true,
        cacheControl: "31536000",
      });

    if (upErr) {
      console.error("Upload error:", upErr);
      // Still return inline so client can play (data URL fallback could be added)
      return new Response(JSON.stringify({ error: "Upload failed", detail: upErr.message }), {
        status: 500,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    return new Response(JSON.stringify({ url: oaUrl, cached: false, provider: "openai" }), {
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });

  } catch (e: any) {
    console.error("tts function error:", e);
    return new Response(JSON.stringify({ error: e.message || "Unknown error" }), {
      status: 500,
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  }
});
